version: "3"

services: 
        
    backend:
        build: 
            dockerfile: Dockerfile
            context: ./backend
        ports: 
            - 4000:4000
        restart: on-failure
        
        volumes: 
            - /app/node_modules
            - ./backend/prisma:/app/prisma
            - ./backend/src:/app/src
            - ./backend/__test__/faker:/app/__test__/faker
    